urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.template import add_to_builtins
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    (r'^snippets/', include('quest.urls')),
    (r'^users/', include('users.urls')),
    (r'^feeds/', include('feeds.urls')),
)

urlpatterns += patterns('quest.views',
    (r'^$', 'view_homepage', {'homepage_template':'homepage.html'}, 'homepage'),
)

urlpatterns += patterns('users.views',
    (r'^accounts/register/$', 'view_register', {'registration_template': 'register.html'}, 'register'),
    (r'^accounts/login/$', 'view_login', {'login_template': 'login.html'}, 'login'),
    (r'^accounts/logout/$', 'view_logout', {'logout_template': 'logout.html'}, 'logout')
)

add_to_builtins("utils.templatetags.tags")

users/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('users.views',
    (r'^$', 'view_all_users', {'all_users_template':'all_users.html'}, 'all_users'),
    (r'^(?P<user_id>\d+)/(?P<user_slug_name>[\w-]+)/$', 'view_userprofile', {'userprofile_template':'user_profile.html'}, 'user_profile'),
)

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from utils.models import BaseModel, BaseModelManager
import hashlib

class UserProfileAlreadyExistsException(Exception):
    pass

class UserProfileManager(BaseModelManager):
    def create_userprofile(self, email, password, name=''):
        if self.exists(email=email):
            raise UserProfileAlreadyExistsException
        user = User.objects.create_user(username=self._compute_username(email),
                                        email=email,
                                        password=password)
        userprofile = UserProfile(user=user, email=email, name=name, slug=slugify(name))
        userprofile.save()
        return userprofile

    def _compute_username(self, email):
        return hashlib.sha1(email).hexdigest()[:30]

    def exists(self, **params):
        return self.filter(**params).count()
    
    def update_userprofile(self, existing_userprofile, **params):
        password = params.pop('password', '')
        if password:
            user = existing_userprofile.user 
            user.set_password(password)
            user.save()
        if params.has_key('name') and not params.pop('slug', ''):
            params['slug'] = slugify(params.get('name')) 
        for parameter in params:
            setattr(existing_userprofile, parameter, params.get(parameter))
        existing_userprofile.save()
        return existing_userprofile

class UserProfile(BaseModel):
    user = models.OneToOneField(User)
    email = models.EmailField(max_length=100, unique=True, db_index=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=50, db_index=True) 
    objects = UserProfileManager()
    
    def __unicode__(self):
        return self.email
    
    def submitted_snippets(self):
        return [membership.snippet for membership in self.userprofilesnippetmembership_set.select_related()]
        

users/forms.py
from django import forms
from users.models import UserProfile

class RegistrationForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=100, required=True)
    password = forms.CharField(max_length=128, required=True, widget=forms.PasswordInput())
    next_url = forms.CharField(max_length=128, required=False, widget=forms.HiddenInput())
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            UserProfile.objects.get(email=email)
            raise forms.ValidationError("Email-id already taken! Please pick a different email")
        except UserProfile.DoesNotExist:
            return email
    
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True)
    password = forms.CharField(max_length=128, required=True, widget=forms.PasswordInput())
    next_url = forms.CharField(max_length=128, required=False, widget=forms.HiddenInput())
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            UserProfile.objects.get(email=email)
            return email
        except UserProfile.DoesNotExist:
            raise forms.ValidationError("Invalid Email and/or Password")

users/views.py
from django.contrib.auth import authenticate as django_authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.core.urlresolvers import reverse as url_reverse
from django.http import HttpResponseRedirect
from users.models import UserProfile
from utils import response, post_data
from users.decorators import anonymoususer
from django.shortcuts import get_object_or_404
import django_messages_framework 

def view_all_users(request, all_users_template):
    from django.core.paginator import Paginator, EmptyPage, InvalidPage
    paginator = Paginator(UserProfile.objects.values('id', 'name', 'email', 'slug'), 2)
    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        page = 1
    try:
        users = paginator.page(page)
    except (EmptyPage, InvalidPage):
        users = paginator.page(paginator.num_pages)
    return response(request, all_users_template, {'users': users})

@anonymoususer
def view_register(request, registration_template, next=''):
    from users.forms import RegistrationForm
    if request.method == 'POST':
        form = RegistrationForm(post_data(request))
        if form.is_valid():
            userprofile = _handle_user_registration(form)
            from users.messages import USER_SIGNUP_SUCCESSFUL
            django_messages_framework.success(request, USER_SIGNUP_SUCCESSFUL)
            return _let_user_login(request,
                                   userprofile.user,
                                   email=form.cleaned_data.get('email'),
                                   password=form.cleaned_data.get('password'),
                                   next=form.cleaned_data.get('next'))
    else:
        form = RegistrationForm()
    return response(request, registration_template, {'form': form, 'next': next})

def _handle_user_registration(registration_form):
    userprofile = UserProfile.objects.create_userprofile(email=registration_form.cleaned_data.get('email'),
                                           password=registration_form.cleaned_data.get('password'),
                                           name=registration_form.cleaned_data.get('name'))
    return userprofile

def _authenticate_user(user):
    raise NotImplementedError

def _let_user_login(request, user, email, password, next=''):
    user = django_authenticate(username=email, password=password)
    django_login(request, user)
    if next:
        return HttpResponseRedirect(redirect_to=next)
    return HttpResponseRedirect(redirect_to=url_reverse('quest.views.view_homepage'))

@anonymoususer
def view_login(request, login_template, next=''):
    from users.forms import LoginForm
    if request.method == 'POST':
        form = LoginForm(post_data(request))
        if form.is_valid():
            userprofile = UserProfile.objects.get(email=form.cleaned_data.get('email'))
            if not userprofile.user.check_password(form.cleaned_data.get('password')):
                from users.messages import USER_LOGIN_FAILURE
                django_messages_framework.error(request, USER_LOGIN_FAILURE)
                return response(request, login_template, {'form': form, 'next': next})
            from users.messages import USER_LOGIN_SUCCESSFUL
            django_messages_framework.success(request, USER_LOGIN_SUCCESSFUL)
            return _let_user_login(request,
                                   userprofile.user,
                                   email=form.cleaned_data.get('email'),
                                   password=form.cleaned_data.get('password'),
                                   next=form.cleaned_data.get('next'))
    else:
        form = LoginForm()
    return response(request, login_template, {'form': form, 'next': next})

def view_logout(request, logout_template):
    django_logout(request)
    from users.messages import USER_LOGOUT_SUCCESSFUL
    django_messages_framework.info(request, USER_LOGOUT_SUCCESSFUL)
    return HttpResponseRedirect(redirect_to=url_reverse('quest.views.view_homepage'))

def view_userprofile(request, user_id, user_slug_name, userprofile_template):
    userprofile = get_object_or_404(UserProfile, id=int(user_id), slug=user_slug_name)
    submitted_snippets = [{'title': snippet.title,
                           'slug': snippet.slug,
                           'id': snippet.id,
                           'active': snippet.active} for snippet in userprofile.submitted_snippets()]
    return response(request, userprofile_template, {'userprofile': userprofile,
                                                    'submitted_snippets': submitted_snippets})

users/templates/all_users.html
{%extends 'singlepane_base.html'%}
{%block title%}All Users{%endblock%}
{%block content%}
<h3>List of Users</h3>
<ul>
{%for user in users.object_list%}
    <li><a href="{%url user_profile user_id=user.id user_slug_name=user.slug%}">{{user.name|title}}</a></li>
{%empty%}
    <li>No Users as of now</li>
{%endfor%}
</ul>
{%pagination users%}
{%endblock%}

users/templates/login.html
{%extends 'singlepane_base.html'%}
{% block title %}Login{% endblock %}
{%block content%}
<div class='prepend-8'>
	<form action="{%url login%}" method='POST'>
	<input type='hidden' name='next' value="{{next}}"/>
	<table class='form-table'>
	    <tr><td class='form-row'><label for="id_email">Email</label></td><td class='form-row'>{{form.email}}{{form.email.errors}}</td></tr>
	    <tr><td class='form-row'><label for="id_password">Password</label></td><td class='form-row'>{{form.password}}{{form.password.errors}}</td></tr>
	    <tr><td>&nbsp;</td><td><input type='submit' name='submit' value="Log in"/></td></tr>
	</table>
	</form>
</div>
{%endblock%}

users/templates/logout.html
You will be logged out

users/templates/register.html
{%extends 'singlepane_base.html'%}
{% block title %}Create a User Account{% endblock %}
{%block content%}
<div class='prepend-8'>
    <form action="{%url register%}" method='POST'>
	<input type='hidden' name='next' value="{{next}}"/>
	<table class='form-table'>
	    <tr><td class='form-row'><label for="id_name">Name</label></td><td class='form-row'>{{form.name}}<br/>{{form.name.errors}}</td></tr>
	    <tr><td class='form-row'><label for="id_email">Email</label></td><td class='form-row'>{{form.email}}{{form.email.errors}}</td></tr>
	    <tr><td class='form-row'><label for="id_password">Password</label></td><td class='form-row'>{{form.password}}{{form.password.errors}}</td></tr>
	    <tr><td>&nbsp;</td><td><input type='submit' name='submit' value="Create my Account"/></td></tr>
	</table>
	</form>
</div>
{%endblock%}

users/templates/user_profile.html
{%extends 'singlepane_base.html'%}
{% block title %}User {{userprofile.name|title}}{% endblock %}
{%block content%}
<h3>This is the profile page</h3>
<div class='column span-24 last'>
<table>
<tr><td class='strong'>Name:</td><td>{{userprofile.name|title}}</td></tr>
<tr><td>Email:</td><td><a href='mailto:{{userprofile.email}}'>{{userprofile.email}}</a></td></tr>
<tr><td>Contributed Snippets</td>
<td>
<ul>
{%for snippet in submitted_snippets%}
    <li><a href="{%url snippet_profile snippet_id=snippet.id snippet_slug=snippet.slug%}">{{snippet.title|title}}</a></li>
{%empty%}
No Contributed Snippets, as of now
{%endfor%}
</ul>
</td>
</tr>
</table>
</div>
<br/><br/><br/>
<a href="{%url all_users%}">All Users</a>
{%endblock%}