quest/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('quest.views',
    (r'^$', 'view_all_snippets', {'all_snippets_template':'all_snippets.html'}, 'all_snippets'),
    (r'^search/$', 'view_search_snippets', {'search_snippets_template':'search_snippets.html'}, 'search_snippets'),
    (r'^tags/$', 'view_tagcloud_snippets', {'tagcloud_snippets_template':'tagcloud_snippets.html'}, 'tagcloud_snippets'),
    (r'^recent/$', 'view_recent_snippets', {'recent_snippets_template':'recent_snippets.html'}, 'recent_snippets'),
    (r'^popular/$', 'view_popular_snippets', {'popular_snippets_template':'popular_snippets.html'}, 'popular_snippets'),
    (r'^(?P<snippet_id>\d+)/(?P<snippet_slug>[\w-]+)/$', 'view_snippet_profile', {'snippet_profile_template':'snippet_profile.html'}, 'snippet_profile'),
    (r'^add/$', 'view_add_snippet', {'add_snippet_template':'add_snippet.html', 'snippet_profile_template':'snippet_profile.html'}, 'add_snippet'),
    (r'^(?P<snippet_id>\d+)/(?P<snippet_slug>[\w-]+)/delete/$', 'view_delete_snippet', {}, 'delete_snippet'),
    (r'^(?P<snippet_id>\d+)/(?P<snippet_slug>[\w-]+)/modify/$', 'view_modify_snippet', {'modify_snippet_template':'add_snippet.html', 'snippet_profile_template':'snippet_profile.html'}, 'modify_snippet'),
    (r'^(?P<tag_name>[\w-]+)/$', 'view_tagged_snippets', {'tagged_snippets_template':'all_snippets.html'}, 'tagged_snippets'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.template import add_to_builtins
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    (r'^snippets/', include('quest.urls')),
    (r'^users/', include('users.urls')),
    (r'^feeds/', include('feeds.urls')),
)

urlpatterns += patterns('quest.views',
    (r'^$', 'view_homepage', {'homepage_template':'homepage.html'}, 'homepage'),
)

urlpatterns += patterns('users.views',
    (r'^accounts/register/$', 'view_register', {'registration_template': 'register.html'}, 'register'),
    (r'^accounts/login/$', 'view_login', {'login_template': 'login.html'}, 'login'),
    (r'^accounts/logout/$', 'view_logout', {'logout_template': 'logout.html'}, 'logout')
)

add_to_builtins("utils.templatetags.tags")

quest/models.py
from django.contrib.auth.models import AnonymousUser
from django.db import models
from django.template.defaultfilters import slugify
from django.template.defaultfilters import striptags
from django.utils.safestring import mark_safe
from users.models import UserProfile
from utils import language_choices
from utils.models import BaseModel, BaseModelManager
from tagging.models import Tag

class UserAlreadyCreatedSnippetException(Exception):
    pass

class ActiveSnippetManager(models.Manager):
    def get_query_set(self):
        return super(ActiveSnippetManager, self).get_query_set().filter(active=True)

class PublicSnippetManager(models.Manager):
    def get_query_set(self):
        return super(PublicSnippetManager, self).get_query_set().filter(public=True)

class SnippetManager(models.Manager):
    def create_snippet(self, title, explanation, code, lang, tags, public=True, active=True):
        title = striptags(title)
        explanation = striptags(explanation)
        code = striptags(code)
        snippet = Snippet(title=title, slug=slugify(title), explanation=explanation, code=code, lang=lang, public=public, active=active)
        snippet.save()
        Tag.objects.update_tags(snippet, tags)
        return snippet

    def update_snippet(self, existing_snippet, **params):
        for key, value in params.items():
            if isinstance(value, str) or isinstance(value, unicode):
                params[key] = striptags(value)
        if params.has_key('tags'):
            Tag.objects.update_tags(existing_snippet, params.pop('tags'))
        for param in params:
            setattr(existing_snippet, param, params[param])
        existing_snippet.save()
        return Snippet.objects.get(id=existing_snippet.id)

class Snippet(BaseModel):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    explanation = models.TextField(max_length=200)
    code = models.TextField(max_length=1500)
    lang = models.CharField(max_length=10, choices=language_choices)
    public = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    objects = SnippetManager()
    publicsnippets = PublicSnippetManager()
    activesnippets = ActiveSnippetManager()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('snippet_profile', (self.id, self.slug))
    
    def tags(self):
        return Tag.objects.get_for_object(self)
    
    def assign_tags(self, tags_text):
        Tag.objects.update_tags(self, tags_text)
        return self
    
    def clear_tags(self):
        Tag.objects.update_tags(self, None)
        return self

    def get_owner(self):
        try:
            return UserProfileSnippetMembership.objects.get(snippet=self).userprofile
        except UserProfileSnippetMembership.DoesNotExist:
            return AnonymousUser()

    owner = property(get_owner)

    def save(self, force_insert=False, force_update=False):
        self.title = striptags(self.title)
        self.explanation = striptags(self.explanation)
        self.code = striptags(self.code)
        super(Snippet, self).save(force_insert=force_insert,
                                  force_update=force_update)

    def get_lexer(self):
        from pygments.lexers import get_lexer_by_name
        if self.lang == 'py':
            return get_lexer_by_name('python')
        elif self.lang == 'sql':
            return get_lexer_by_name('sql')
        elif self.lang == 'js':
            return get_lexer_by_name('js')
        elif self.lang == 'html':
            return get_lexer_by_name('html')
        else:
            raise NotImplementedError

    def highlight(self):
        try:
            from pygments import formatters
            formatter = formatters.HtmlFormatter
            from pygments import highlight as syntax_highlight
            return mark_safe(syntax_highlight(self.code,
                                              self.get_lexer(),
                                              formatters.HtmlFormatter(linenos='table',
                                                                       lineanchors='line',
                                                                       anchorlinenos=True)))
        except ImportError:
            return mark_safe(self.code)

    def activate(self):
        if not self.active:
            self.active = True
            self.save()
            return self
        return None

    def close(self):
        if self.active:
            self.active = False
            self.save()
            return self
        return None

    deactivate = close

    def hide(self):
        if self.public:
            self.public = False
            self.save()
            return self
        return None

    private = hide

    def make_public(self):
        if not self.public:
            self.public = True
            self.save()
            return self
        return None

    def toggle_visibility(self):
        self.public = not self.public
        self.save()
        return self
    
class UserProfileSnippetMembershipManager(BaseModelManager):
    def create_membership(self, userprofile, snippet):
        if self.exists(userprofile=userprofile, snippet=snippet):
            raise UserAlreadyCreatedSnippetException
        membership = UserProfileSnippetMembership(userprofile=userprofile,
                                                  snippet=snippet)
        membership.save()
        return membership

    def exists(self, userprofile, snippet):
        if self.filter(userprofile=userprofile, snippet=snippet).count():
            return True
        return False

class UserProfileSnippetMembership(BaseModel):
    userprofile = models.ForeignKey(UserProfile)
    snippet = models.ForeignKey(Snippet)
    objects = UserProfileSnippetMembershipManager()

    def __unicode__(self):
        return '%s - %s' % (self.userprofile, self.snippet.slug)

quest/forms.py
from django import forms
from utils import language_choices
from tagging.forms import TagField 

class AddSnippetForm(forms.Form):
    title = forms.CharField(required=True, max_length=100)
    explanation = forms.CharField(required=True, max_length=200)
    code = forms.CharField(required=True, widget=forms.Textarea({'rows':'10', 'cols':'50'}))
    public = forms.BooleanField(required=False, initial=True)
    lang = forms.ChoiceField(choices=language_choices, required=True)
    tags = TagField(required=True, max_length=100)
    
class SearchSnippetForm(forms.Form):
    query = forms.CharField(required=True, max_length=50)

quest/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.core.urlresolvers import reverse as url_reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from quest.decorators import is_snippetowner
from quest.models import Snippet
from types import NotImplementedType
from utils import response, post_data
import django_messages_framework
from tagging.models import Tag, TaggedItem
from django.conf import settings

def view_homepage(request, homepage_template):
    return response(request, homepage_template, locals())

def view_all_snippets(request, all_snippets_template):
    paginator = Paginator(Snippet.publicsnippets.values('id', 'title', 'active', 'slug'), settings.PAGINATION_ITEMS_SIZE)
    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        page = 1
    try:
        snippets = paginator.page(page)
    except (EmptyPage, InvalidPage):
        snippets = paginator.page(paginator.num_pages)
    return response(request, all_snippets_template, {'snippets': snippets})

def view_snippet_profile(request, snippet_id, snippet_slug, snippet_profile_template):
    snippet = get_object_or_404(Snippet, id=int(snippet_id), slug=snippet_slug)
    user = request.user
    owner = False
    if user.is_authenticated() and snippet.owner == user.get_profile():
        owner = True
    return response(request, snippet_profile_template, {'snippet': snippet,
                                                        'owner': owner})

def view_recent_snippets(request, recent_snippets_template):
    raise NotImplementedError

def view_popular_snippets(request, popular_snippets_template):
    raise NotImplementedError

def view_add_snippet(request, add_snippet_template, snippet_profile_template):
    user = request.user
    from quest.forms import AddSnippetForm
    if request.method == 'POST':
        form = AddSnippetForm(post_data(request))
        if form.is_valid():
            snippet = _handle_snippet_creation(form)
            owner = False
            if user.is_authenticated():
                userprofile = user.get_profile()
                owner = True
                from quest.models import UserProfileSnippetMembership
                UserProfileSnippetMembership.objects.create_membership(userprofile=userprofile,
                                                                      snippet=snippet)
            from quest.messages import SNIPPET_CREATION_SUCCESSFUL
            django_messages_framework.success(request, SNIPPET_CREATION_SUCCESSFUL)
            return response(request, snippet_profile_template, {'snippet': snippet,
                                                                'owner': owner})
    else:
        form = AddSnippetForm()
        if not user.is_authenticated():
            form.fields.get('public').widget.attrs = {'readonly': True, 
                                                      'disabled': 'disabled'}
    return response(request, add_snippet_template, {'form': form})

def view_delete_snippet(request, snippet_id, snippet_slug):
    existing_snippet = get_object_or_404(Snippet, id=int(snippet_id), slug=snippet_slug)
    existing_snippet.delete()
    #TODO:It should tell a message telling the snippet is deleted
    return HttpResponseRedirect(redirect_to=url_reverse('quest.views.view_all_snippets'))

@login_required
@is_snippetowner
def view_modify_snippet(request, snippet_id, snippet_slug, modify_snippet_template, snippet_profile_template):
    modify = True
    from quest.forms import AddSnippetForm
    if request.method == 'POST':
        form = AddSnippetForm(post_data(request))
        existing_snippet = Snippet.objects.get(id=snippet_id)
        if form.is_valid():
            updated_snippet = _handle_snippet_updation(form, existing_snippet)
            from quest.messages import SNIPPET_UPDATION_SUCCESSFUL
            django_messages_framework.success(request, SNIPPET_UPDATION_SUCCESSFUL)
            return response(request, snippet_profile_template, {'snippet': updated_snippet,
                                                                'owner': True})
        return response(request, modify_snippet_template, {'form': form})
    else:
        snippet = Snippet.objects.get(id=snippet_id)
        form_data = {'title':snippet.title,
                     'explanation':snippet.explanation,
                     'code':snippet.code,
                     'public':snippet.public,
                     'lang':snippet.lang,
                     'tags':" ".join([tag.name for tag in snippet.tags()])}
        form = AddSnippetForm(form_data)
        return response(request, modify_snippet_template, {'form':form,
                                                           'snippet': snippet,
                                                           'modify':modify})

def _handle_snippet_creation(form):
    snippet_data = form.cleaned_data
    title = snippet_data.get('title')
    code = snippet_data.get('code')
    explanation = snippet_data.get('explanation')
    public = snippet_data.get('public')
    lang = snippet_data.get('lang')
    tags = snippet_data.get('tags')
    return Snippet.objects.create_snippet(title=title,
                                          explanation=explanation,
                                          code=code,
                                          lang=lang,
                                          public=public,
                                          tags=tags)

def _handle_snippet_updation(form, existing_snippet):
    snippet_data = form.cleaned_data
    return Snippet.objects.update_snippet(existing_snippet,
                                          title=snippet_data.get('title'),
                                          explanation=snippet_data.get('explanation'),
                                          code=snippet_data.get('code'),
                                          lang=snippet_data.get('lang'),
                                          public=snippet_data.get('public'),
                                          tags=snippet_data.get('tags'))
    
def view_search_snippets(request, search_snippets_template):
    from quest.forms import SearchSnippetForm
    if request.method == 'POST':
        form = SearchSnippetForm({'query': request.POST.get('query')})
        if form.is_valid():
            query = form.cleaned_data.get('query')
            #TODO:Should also support tagbased search
            paginator = Paginator(Snippet.objects.filter(title__icontains=query).values('id', 'title', 'active', 'slug'), settings.PAGINATION_ITEMS_SIZE)
            try:
                page = int(request.GET.get('page', 1))
            except ValueError:
                page = 1
            try:
                snippets = paginator.page(page)
            except (EmptyPage, InvalidPage):
                snippets = paginator.page(paginator.num_pages)
            return response(request, search_snippets_template, {'form': form, 'snippets': snippets})
    else:
        form = SearchSnippetForm()
    return response(request, search_snippets_template, {'form': form, 'snippets': []})

def view_tagged_snippets(request, tag_name, tagged_snippets_template):
    tag = get_object_or_404(Tag, name=tag_name)
    snippets = [tagged_item.object for tagged_item in TaggedItem.objects.filter(tag=tag) if tagged_item.object]
    paginator = Paginator(snippets, 1)
    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        page = 1
    try:
        snippets = paginator.page(page)
    except (EmptyPage, InvalidPage):
        snippets = paginator.page(paginator.num_pages)
    return response(request, tagged_snippets_template, {'snippets': snippets,
                                                        'tag': tag})
    
def view_tagcloud_snippets(request, tagcloud_snippets_template):
    #FIXME:Could be in a generic view ? as its empty!
    return response(request, tagcloud_snippets_template, {})

quest/templates/add_snippet.html
{%extends 'singlepane_base.html'%}
{%block title%}{%if modify%}Modify{%else%}Add a new{%endif%} Snippet{%endblock%}
{%block content%}
<h4>{%if modify%}Modify Snippet{%else%}Add a new Snippet.<br/><span class='small_text'>( You are anonymous! Which means, this script will be public! )</span>{%endif%}</h4>
<form action="." method='POST'>
<table class='form-table'>
    <tr><td class='form-row'><label for="id_title">Title</label></td><td class='form-row'>{{form.title}}<br/>{{form.title.errors}}</td></tr>
    <tr><td class='form-row'><label for="id_explanation">Explanation</label></td><td class='form-row'>{{form.explanation}}{{form.explanation.errors}}</td></tr>
    <tr><td class='form-row'><label for="id_code">Code</label></td><td class='form-row'>{{form.code}}{{form.code.errors}}</td></tr>
    <tr><td class='form-row'><label for="id_public">Make Code Public</label></td><td class='form-row'>{{form.public}}{{form.public.errors}}</td></tr>
    <tr><td class='form-row'><label for="id_lang">Language</label></td><td class='form-row'>{{form.lang}}{{form.lang.errors}}</td></tr>
    <tr><td class='form-row'><label for="id_tags">Tags</label></td><td class='form-row'>{{form.tags}}{{form.tags.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input type='submit' name='submit' value='{%if modify%}Modify{%else%}Add{%endif%} Snippet'/></td></tr>
</table>
</form>
<a href='{%url all_snippets%}'>All Snippets</a>
{%endblock%}

quest/templates/all_snippets.html
{%extends 'singlepane_base.html'%}
{%block title%}{%if tag%}{{tag.name|title}}{%else%}List of{%endif%} Snippets{%endblock%}
{%block content%}
<link href="{%url feeds 'snippets'%}" title="Latest Snippets - RSS - ZeShare" type="application/rss+xml" rel="alternate">
<h3>{%if tag%}{{tag.name|title}}{%else%}List of{%endif%} Snippets</h3>
<ul>
<!-- There is a reason why I didn't use snippet.get_absolute_url -->
{%for snippet in snippets.object_list%}
    <li><a href="{%url snippet_profile snippet_id=snippet.id snippet_slug=snippet.slug%}">{{snippet.title|title}}</a></li>
{%empty%}
    <li>No Snippets as of now. <a href='{%url add_snippet%}'>Want to create ?</a></li>
{%endfor%}
</ul>
{%pagination snippets%}
{%endblock%}

quest/templates/popular_snippets.html
This is the popular snippets page

quest/templates/recent_snippets.html
This is the recent snippets page

quest/templates/search_snippets.html
{%extends 'singlepane_base.html'%}
{%block title%}Search Code Snippets{%endblock%}
{%block content%}
<form action='.' method='POST'>
<table class='form-table'>
    <tr><td class='form-row'><label for="id_query">Search</label></td><td class='form-row'>{{form.query}}{{form.query.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input type='submit' value='Search Snippets' name='submit'/></td></tr>
</table>
</form>
{%with snippets.object_list as snippet_results%}
	{%if snippet_results%}
	    <ul>
	    {%for snippet in snippet_results%}
	        <li><a href="{%url snippet_profile snippet_id=snippet.id snippet_slug=snippet.slug%}">{{snippet.title|title}}</a></li>
		{%endfor%}
		{% pagination snippets%}
		</ul>
	{%endif%}
{%endwith%}
{%endblock%}

quest/templates/snippet_profile.html
{%extends 'singlepane_base.html'%}
{% block title %}{{snippet.title|title}}{% endblock %}
{%block extrastyle%}
<link rel="stylesheet" type="text/css" media="screen" href="/site_media/css/pygments/tango.css"/>
<link rel="stylesheet" type="text/css" media="print" href="/site_media/css/blueprint/print.css"/>
{%endblock%}
{%block content%}
<div id='snippet_content'>
{{message}}
<h3><a href='{%url snippet_profile snippet.id snippet.slug%}'>{{snippet.title|title}}</a></h3>
<div id='snippet_description'>{{snippet.explanation}}</div>
{%if owner %}
<a onClick="javascript:document.location.href='{%url modify_snippet snippet.id snippet.slug%}'" href="javascript:;">Edit</a>&nbsp;|&nbsp;
<a onClick="javascript:document.location.href='{%url delete_snippet snippet.id snippet.slug%}'" href="javascript:;">Delete</a>&nbsp;|&nbsp;
{%endif%}
<div class='snippet'><pre>{{snippet.highlight}}</pre></div>
{%load tagging_tags%}
{% tags_for_object snippet as tag_list %}
<span id='tags_header'>Tags:</span>{%for tag in tag_list%}
<a title="Browse {{tag.name|title}} snippets" href="{%url tagged_snippets tag_name=tag.name%}"><span class="tag">{{tag.name}}</span></a>&nbsp;&nbsp;
{%endfor%}
<br/><br/>
<h5><a href="{%url all_snippets%}">All Snippets</a></h5>
</div>
{%endblock%}

quest/templates/tagcloud_snippets.html
{%extends 'singlepane_base.html'%}
{% block title %}Tag Cloud for Snippets{% endblock %}
{%block content%}
<h3>Tag Cloud for Snippets</h3>
{%load tagging_tags%}
{% tag_cloud_for_model quest.Snippet as snippets_tags with steps=3%}
{%for snippets_tag in snippets_tags%}
<a title="Browse {{snippets_tag.name|title}} snippets" href="{%url tagged_snippets tag_name=snippets_tag.name%}"><span class="tag" style='font-size:{{snippets_tag.font_size}}em;'>{{snippets_tag.name}}</span></a>&nbsp;&nbsp;
{%endfor%}
<h5><a href="{%url all_snippets%}">All Snippets</a></h5>
{%endblock%}